"""AgentRun domain entity.

Represents a single agent execution lifecycle from natural language
query submission through SQL generation, validation, and execution.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import StrEnum
from typing import Any


class AgentRunStatus(StrEnum):
    """Lifecycle states for an agent run."""

    PENDING = "pending"
    RUNNING = "running"
    AWAITING_APPROVAL = "awaiting_approval"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class AgentPersona(StrEnum):
    """Supported Agency Agent specialist personas for NexusBI."""

    DATA_ANALYST = "data_analyst"
    SQL_DATA = "sql_data"
    DASHBOARD_BI = "dashboard_bi"
    CODE_ENGINEERING = "code_engineering"
    ORCHESTRATOR = "orchestrator"


class AgentStepName(StrEnum):
    """Named steps in the NL→SQL agent pipeline."""

    SCHEMA_RESOLVE = "schema_resolve"
    SQL_GENERATE = "sql_generate"
    SQL_VALIDATE = "sql_validate"
    QUERY_EXECUTE = "query_execute"
    PERSONA_EXECUTE = "persona_execute"


@dataclass
class StepRecord:
    """Immutable record of a single pipeline step execution.

    Attributes
    ----------
    step_name : str
        The pipeline step identifier.
    status : str
        Step outcome: 'success', 'error', 'skipped'.
    started_at : datetime
        When the step began executing.
    completed_at : datetime | None
        When the step finished, or None if still running.
    latency_ms : float
        Step execution time in milliseconds.
    input_summary : str
        Brief summary of step input (for observability, not full content).
    output_summary : str
        Brief summary of step output.
    error : str | None
        Error message if step failed.
    metadata : dict[str, Any]
        Additional step-specific metadata.
    """

    step_name: str
    status: str = "pending"
    started_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    completed_at: datetime | None = None
    latency_ms: float = 0.0
    input_summary: str = ""
    output_summary: str = ""
    error: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class AgentRun:
    """Domain entity representing a complete agent execution.

    Tracks the full lifecycle of an NL→SQL agent run, including
    all pipeline steps, generated artifacts, and audit metadata.

    Attributes
    ----------
    id : str
        Unique run identifier (UUID).
    user_id : str
        The authenticated user who initiated the run.
    organization_id : str | None
        Optional organization scope.
    workspace_id : str | None
        Optional workspace scope.
    dataset_id : str
        The target dataset for query generation.
    natural_language_query : str
        The user's original natural language question.
    generated_sql : str | None
        The SQL generated by the LLM, if successful.
    status : AgentRunStatus
        Current lifecycle state.
    confidence : float
        LLM's confidence in the generated SQL (0.0 to 1.0).
    steps : list[StepRecord]
        Ordered list of pipeline step execution records.
    total_tokens : int
        Total LLM tokens consumed across all steps.
    total_cost_usd : float
        Estimated total cost in USD.
    error : str | None
        Top-level error message if the run failed.
    created_at : datetime
        When the run was created.
    updated_at : datetime
        When the run was last modified.
    """

    id: str
    user_id: str
    natural_language_query: str
    dataset_id: str | None = None
    organization_id: str | None = None
    workspace_id: str | None = None
    agent_role: str = "sql_data"
    generated_sql: str | None = None
    insights: str | None = None
    visualization_config: dict[str, Any] = field(default_factory=dict)
    code_snippet: str | None = None
    query_result: dict[str, Any] | None = None
    status: AgentRunStatus = AgentRunStatus.PENDING
    confidence: float = 0.0
    steps: list[StepRecord] = field(default_factory=list)
    total_tokens: int = 0
    total_cost_usd: float = 0.0
    error: str | None = None
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    updated_at: datetime = field(default_factory=lambda: datetime.now(UTC))

    def add_step(self, step: StepRecord) -> None:
        """Append a step record and update the run timestamp."""
        self.steps.append(step)
        self.updated_at = datetime.now(UTC)

    def mark_running(self) -> None:
        """Transition the run to RUNNING status."""
        self.status = AgentRunStatus.RUNNING
        self.updated_at = datetime.now(UTC)

    def mark_completed(self, generated_sql: str, confidence: float) -> None:
        """Transition the run to COMPLETED with generated SQL."""
        self.status = AgentRunStatus.COMPLETED
        self.generated_sql = generated_sql
        self.confidence = confidence
        self.updated_at = datetime.now(UTC)

    def mark_failed(self, error: str) -> None:
        """Transition the run to FAILED with an error message."""
        self.status = AgentRunStatus.FAILED
        self.error = error
        self.updated_at = datetime.now(UTC)

    def accumulate_cost(self, tokens: int, cost_usd: float) -> None:
        """Add token and cost usage from an LLM call."""
        self.total_tokens += tokens
        self.total_cost_usd += cost_usd
