"""Agent request/response DTOs.

Defines the API contract for the Agent Gateway endpoints. These schemas
are used for request validation and response serialisation.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

# ---------------------------------------------------------------------------
# Request DTOs
# ---------------------------------------------------------------------------


class AgentQueryRequestDTO(BaseModel):
    """Request body for submitting a natural language query to an agent."""

    model_config = ConfigDict(populate_by_name=True)

    natural_language_query: str = Field(
        ...,
        alias="query",
        min_length=3,
        max_length=2000,
        description="The natural language question to translate to SQL.",
        examples=["What are the top 10 customers by revenue this quarter?"],
    )
    dataset_id: str | None = Field(
        default=None,
        max_length=64,
        description="The target dataset ID to query against.",
    )
    workspace_id: str | None = Field(
        default=None,
        max_length=64,
        description="Optional workspace scope for dataset access.",
    )
    agent_role: str = Field(
        default="sql_data",
        max_length=64,
        description=(
            "Specialist agent persona role (sql_data, data_analyst, "
            "dashboard_bi, code_engineering, orchestrator)."
        ),
    )


# ---------------------------------------------------------------------------
# Response DTOs
# ---------------------------------------------------------------------------


class StepRecordDTO(BaseModel):
    """A single pipeline step execution record."""

    step_name: str
    status: str
    started_at: datetime
    completed_at: datetime | None = None
    latency_ms: float
    error: str | None = None


class AgentQueryResponseDTO(BaseModel):
    """Response body for an agent query execution."""

    run_id: str = Field(description="Unique agent run identifier.")
    status: str = Field(description="Run lifecycle status.")
    agent_role: str = Field(
        default="sql_data", description="The specialist persona executed."
    )
    natural_language_query: str = Field(description="The original NL query.")
    generated_sql: str | None = Field(
        default=None,
        description="The SQL generated by the agent.",
    )
    insights: str | None = Field(
        default=None,
        description="Analytical insights or business recommendations.",
    )
    visualization_config: dict[str, Any] | None = Field(
        default=None,
        description="Recommended visualization configuration from Dashboard BI agent.",
    )
    code_snippet: str | None = Field(
        default=None,
        description="Generated data transformation or pipeline code snippet.",
    )
    result: AgentQueryResultDTO | None = Field(
        default=None,
        description="Query execution results, if available.",
    )
    confidence: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Agent's confidence in the generated SQL.",
    )
    total_tokens: int = Field(default=0, description="Total LLM tokens consumed.")
    total_cost_usd: float = Field(default=0.0, description="Estimated cost in USD.")
    steps: list[StepRecordDTO] = Field(
        default_factory=list,
        description="Pipeline step execution records.",
    )
    error: str | None = Field(default=None, description="Error message if run failed.")
    created_at: datetime = Field(description="When the run was created.")


class AgentQueryResultDTO(BaseModel):
    """Subset of query results returned in the agent response."""

    rows: list[dict[str, Any]] = Field(description="Result rows as dictionaries.")
    columns: list[str] = Field(description="Column names.")
    row_count: int = Field(description="Total number of result rows.")
    execution_time_ms: float = Field(description="Query execution time in ms.")
    truncated: bool = Field(
        default=False,
        description="Whether results were truncated to fit response size.",
    )


class AgentRunSummaryDTO(BaseModel):
    """Lightweight summary of an agent run for list endpoints."""

    run_id: str
    status: str
    agent_role: str = "sql_data"
    natural_language_query: str
    generated_sql: str | None = None
    confidence: float = 0.0
    total_tokens: int = 0
    created_at: datetime


class AgentPersonaSummaryDTO(BaseModel):
    """Summary metadata for available specialist agent personas."""

    role: str = Field(description="Persona identifier.")
    name: str = Field(description="Human readable name.")
    description: str = Field(description="Capabilities and focus area.")


# Update forward references
AgentQueryResponseDTO.model_rebuild()
