"""increase_id_column_lengths_to_64

Revision ID: 7a4a565a821e
Revises: 3b9fdb727200
Create Date: 2026-08-06 17:55:39.645945
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7a4a565a821e'
down_revision: str | Sequence[str] | None = '3b9fdb727200'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dashboards', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('dashboards', 'owner_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('dashboards', 'dataset_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('dashboards', 'workspace_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('datasets', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('datasets', 'connection_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('datasets', 'owner_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('datasets', 'workspace_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('memberships', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('memberships', 'workspace_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('memberships', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('memberships', 'role_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('organizations', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('permissions', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('reports', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('reports', 'dataset_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('reports', 'owner_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('reports', 'workspace_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('role_permissions', 'role_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('role_permissions', 'permission_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('roles', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('sessions', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('sessions', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('user_roles', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('user_roles', 'role_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('widgets', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('widgets', 'dashboard_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('widgets', 'dataset_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('workspaces', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('workspaces', 'organization_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspaces', 'organization_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('workspaces', 'id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('widgets', 'dataset_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('widgets', 'dashboard_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('widgets', 'id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('user_roles', 'role_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('user_roles', 'user_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('sessions', 'user_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('sessions', 'id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('roles', 'id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('role_permissions', 'permission_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('role_permissions', 'role_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('reports', 'workspace_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('reports', 'owner_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('reports', 'dataset_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('reports', 'id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('permissions', 'id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('organizations', 'id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('memberships', 'role_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('memberships', 'user_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('memberships', 'workspace_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('memberships', 'id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('datasets', 'workspace_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('datasets', 'owner_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('datasets', 'connection_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('datasets', 'id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('dashboards', 'workspace_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('dashboards', 'dataset_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('dashboards', 'owner_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('dashboards', 'id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###
